name: joseph
favicon: null
layout_spectrum: 0.8943856505211443
typography_spectrum: 0.4722677296958864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090e0a'
    - '#3e433d'
    - '#9fb3b8'
    - '#68746a'
    - '#c59286'
  brandStrength: 0.5
  lightness: 0.7598938022274524
  saturation: 0.4993459484539926
  rhythmicContrast: 0.7057189624756575
purpose: []
